version: '3.8'

services:
  web:
    image: nginx:1.21-alpine
    container_name: freezy-web
    working_dir: /application
    volumes:
      - ./environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - freezy
    ports:
      - ${EXTERNAL_WEBSERVER_PORT}:80
    restart: unless-stopped

  php:
    build:
      context: environment/php
      args:
          INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    container_name: freezy-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
      - ./environment/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - freezy
    restart: unless-stopped

  database:
    image: mysql:8.0.25
    container_name: freezy-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - freezy
    volumes:
        - freezy-mysql-data:/var/lib/mysql
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: freezy-mailhog
    ports:
      - ${MAIL_PORT}:1025
      - ${MAILHOG_DASHBOARD_PORT}:8025
    networks:
      - freezy
    restart: unless-stopped

networks:
  freezy:
    driver: bridge

volumes:
    freezy-mysql-data:
        name: freezy-mysql-data
