version: '3.8'

services:
  php:
    image: ghcr.io/blumilksoftware/php:8.0
    container_name: freezy-php
    working_dir: /application
    volumes:
      - .:/application
    networks:
      - freezy
    restart: unless-stopped

networks:
  freezy:
    driver: bridge
